print("Count the number of pdb files in the current directory.")
print("Usage: cntpdb")
myPath = os.getcwd()
pdbCounter = len(glob.glob1(myPath,"*.pdb"))
print("Number of pdb files in the current directory: ", pdbCounter)
