cmd.distance("hbonds", "all", "all", "3.2", mode="2")
cmd.set("dash_gap","0.4")
cmd.set("dash_color","grey30")
cmd.set("dash_width","1.5")
cmd.set("dash_length",".25")
print("Enter 'rmhb' to remove the hbonds.")
