<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>py2pml</string>
	</array>
	<key>name</key>
	<string>py2pml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.py2pml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"""</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.py2pml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.pymol.py2pml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i:%(\([a-z_]+\))?#?0?\-?[ ]?\+?([0-9]*|\*)(\.([0-9]*|\*))?[hL]?[a-z%])</string>
					<key>name</key>
					<string>constant.other.placeholder.pymol</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.pymol</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.py2pml</string>
	<key>uuid</key>
	<string>e2be2f73-5e4c-4ae1-b9e7-542d13ce445e</string>
</dict>
</plist>
